permalink: /:year/:month/:day/:title/

# Site Config
title: "pithy"
email: abcde@xyz.com
description: "Blog power by pithy"
keywords: "Guovz"

# User Info Config
twitter_username: pithy
github_username: pithy

# Markdown Config
kramdown:
  input:  GFM
  enable_coderay: true
  coderay:
    coderay_line_numbers:  nil



# URL config
baseurl: ""
url: "http://127.0.0.1:4000"


# pageinate config
paginate: 10
paginate_path: "page/:num"

#scss config
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
# duoshuo_shortname: 

# Google Analystic
# analystic:
